
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\prath\OneDrive\Documents\Skive\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("700x450")
window.configure(bg = "#3A868F")


canvas = Canvas(
    window,
    bg = "#3A868F",
    height = 450,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    350.0,
    225.0,
    image=image_image_1
)

canvas.create_text(
    111.0,
    139.0,
    anchor="nw",
    text="Select your Company",
    fill="#FFFFFF",
    font=("Libre Caslon Text", 11 * -1)
)

canvas.create_text(
    111.0,
    189.0,
    anchor="nw",
    text="Create Username",
    fill="#FFFFFF",
    font=("Libre Caslon Text", 11 * -1)
)

canvas.create_text(
    111.0,
    236.0,
    anchor="nw",
    text="Password",
    fill="#FFFFFF",
    font=("Libre Caslon Text", 11 * -1)
)

canvas.create_text(
    111.0,
    284.0,
    anchor="nw",
    text="Confirm Password",
    fill="#FFFFFF",
    font=("Libre Caslon Text", 11 * -1)
)

canvas.create_text(
    156.0,
    90.0,
    anchor="nw",
    text="Sign Up",
    fill="#FFFFFF",
    font=("Libre Caslon Text", 23 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    201.0,
    171.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=102.0,
    y=159.0,
    width=198.0,
    height=22.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    201.5,
    217.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=103.0,
    y=205.0,
    width=197.0,
    height=22.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    201.5,
    264.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=103.0,
    y=252.0,
    width=197.0,
    height=22.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    201.5,
    312.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=103.0,
    y=300.0,
    width=197.0,
    height=22.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=102.0,
    y=340.0,
    width=198.0,
    height=31.0
)
window.resizable(False, False)
window.mainloop()
